Fixes Darwin X64 build failure - missing distutils (#30)
Resolution of missing distutils for darwin builds

Improvements to build process to catch node-gyp failures

Added prebuild and prebuildify asset counts, and block publishing when incorrect

diff --git a/.github/workflows/Prepare prebuild environment.yml b/.github/workflows/Prepare prebuild environment.yml
--- a/.github/workflows/Prepare prebuild environment.yml
+++ b/.github/workflows/Prepare prebuild environment.yml
@@ -18,6 +18,8 @@ env:
   nodeBuildTargets: -t 19.0.0 -t 20.0.0 -t 21.0.0
   electronBuildTargets: -t 5.0.0 -t 6.0.0 -t 7.0.0 -t 8.0.0 -t 9.0.0 -t 10.0.0 -t 11.0.0 -t 12.0.0 -t 13.0.0 -t 14.0.0 -t 15.0.0 -t 16.0.0 -t 17.0.0 -t 18.0.0
   winIA32: -t 10.0.0 -t 11.0.0 -t 12.0.0 -t 13.0.0 -t 14.0.0 -t 15.0.0 -t 16.0.0 -t 17.0.1
+  ReleasePrebuildCount: 280
+  ReleasePrebuildifyCount: 84
 
 jobs:
   Prepare_prebuild_environment:
@@ -270,6 +272,7 @@ jobs:
     - name: macOS - Prebuild Binaries
       if: runner.os == 'macOS'
       run: |
+        python3 -m pip install packaging setuptools
         npm ci --ignore-scripts
         env JOBS=max node .prebuild/prebuild.js ${oldNodeBuildTargets} ${nodeBuildTargets} 
         env JOBS=max node .prebuild/electron.js ${electronBuildTargets}
@@ -349,6 +352,20 @@ jobs:
         run: |
           npm ci --ignore-scripts
           npm run build
+
+      - name: Check Release prebuilds exist
+        shell: bash
+        run: |
+          fileCount=$(ls prebuilds/*/node-pty*tar.gz | wc -l)
+          echo "Release Prebuild count ${fileCount}"
+          if [ "$fileCount" -ne ${ReleasePrebuildCount} ]; then echo "::error::Release Prebuild count ${fileCount}, expected ${ReleasePrebuildCount}"; exit 1; else echo "::notice::Release Prebuild count ${fileCount}, expected ${ReleasePrebuildCount}"; fi
+
+      - name: Check Release prebuildify`s exist
+        shell: bash
+        run: |
+          fileCount=$(ls prebuilds/*/node*node | wc -l)
+          echo "Release Prebuild count ${fileCount}"
+          if [ "$fileCount" -ne ${ReleasePrebuildifyCount} ]; then echo "::error::Release Prebuildify count ${fileCount}, expected ${ReleasePrebuildifyCount}"; exit 1; else echo "::notice::Release Prebuildify count ${fileCount}, expected ${ReleasePrebuildifyCount}"; fi
 
       - name: get-npm-version
         id: package-version
